hero:
  variant: "fullscreen" # Options: classic, split, fullscreen, none
  background:
    tone: "aurora" # Options: none, gradient, solid, aurora
    color: "#103529" # Optional CSS color (hex, rgb, etc.)
  animation: true # Toggle hero animation on/off
  eyebrow: "Welcome"
  title: null
  subtitle: null
  primaryCtaLabel: "Contact Us"
  primaryCtaHref: "/contact"
  secondaryCtaLabel: "Our Services"
  secondaryCtaHref: "/services"
  image: "" #"/images/home-hero.jpg"
statement:
  variant: "centered" # Options: centered, none
  background:
    tone: "none" # Options: none, gradient, solid, aurora
    color: null
  animation: true # Toggle reveal animation on/off
  eyebrow: "What We Believe"
  title: "Driven by clarity, care, and craftsmanship"
  intro: "OBdesign is a small, dedicated web-development business based in Victoria, BC. We focus on creating modern, fast, and functional websites for local businesses that want to a clean online presense. Every project is approached with a balance of design precision and technical skill to ensure your site looks great and performs even better. Collaboration is central to our process—we work closely with each client to understand their goals, audience, and vision. OBdesign provides full end-to-end service, from planning and design to development, launch, and ongoing support. This personal, hands-on approach allows us to deliver high-quality websites built to last and evolve with your business."
services:
  variant: "brief" # Options: grid, list, spotlight, brief, none
  background:
    tone: "aurora" # Options: none, gradient, solid, aurora
    color: "#103529"
  animation: true # Toggle reveal animation on/off
  eyebrow: "What we do"
  title: "Our Services"
  intro: "OBdesign builds fast, mobile-friendly websites, refreshes outdated sites, and boosts visibility through SEO and Google Business optimization."
aboutSection:
  variant: "split"
  background:
    tone: "none"
    color: null
  animation: true
  eyebrow: "About OBdesign"
  title: "A one-person business built on engineering and creativity"
  intro: |
    I’m Owen Brown — a software engineering student at the University of Victoria and the person behind OBdesign. I started this business to combine my technical background with a passion for clean, reliable design that helps small businesses make a strong impression online.

    Every website I build is fast, modern, and easy to maintain, created with the same attention to detail I bring to my software engineering work. I focus on clarity, structure, and long-term reliability so each project feels like an investment that lasts. OBdesign is small by design—personal, transparent, and focused on real results.
  image:
    src: "/images/about-hero.jpg"
    alt: "Owen Brown, founder of OBdesign"
featuredPhotos:
  variant: "none" # Options: grid, none
  background:
    tone: "none" # Options: none, gradient, solid, aurora
    color: null
  animation: true
  items:
    - src: "https://images.unsplash.com/photo-1523475472560-d2df97ec485c?auto=format&fit=crop&w=1200&q=80"
      alt: "Vitamin supplement eCommerce"
    - src: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80"
      alt: "Roofing services website"
    - src: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=80"
      alt: "Community services portal"
featuredProject:
  variant: "project" # Options: project, none
  background:
    tone: "none"
    color: "#103529"
  animation: true
  eyebrow: "Featured project"
  title: "Showcasing a modern home services brand"
  intro: "We partnered with the Uptown Electrical team to redesign their online presence, streamline lead capture, and highlight their customer-first approach."
  image:
    src: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1600&q=80"
    alt: "Featured project hero screen"
  modal:
    title: "Project details"
    body: |
      We rebuilt the UX around homeowner questions, layered in seasonal promotions, and integrated a scheduling workflow that syncs with the team’s dispatch tools.

      Results included a 46% lift in organic enquiries within six weeks, a faster quoting process, and clearer service differentiation across neighborhoods.
portfolioStatement:
  background:
    tone: "aurora" # Options: none, gradient, solid, aurora
    color: "#103529"
  animation: true
  eyebrow: "Our Work"
  title: "Websites built for real results"
  intro: "We design and develop clean, high-performing websites tailored to each business we work with. While our full portfolio is coming soon, you can explore the services and process that power every project we build."
  ctaLabel: "View our Process"
  ctaHref: "/about#process"
cta:
  background:
    tone: "aurora" # Options: none, gradient, solid, aurora
    color: "#103529"
  animation: true
  eyebrow: "Ready to start?"
  title: "Let’s design a website that works for your business"
  intro: "Share your goals and we’ll build a tailored plan—from first concept to launch day and beyond."
  ctaLabel: "Book a call"
  ctaHref: "/contact"
expectations:
  background:
    tone: "none"
    color: null
  animation: true
  eyebrow: "What to expect"
  title: "Dependable collaboration from kickoff to launch"
  intro: "We keep the process transparent, proactive, and personal so you always know what’s happening next—and why."
  items:
    - title: "Clear communication"
      description: "Weekly check-ins, shared milestones, and quick responses keep everyone aligned and confident."
      icon: "💬"
    - title: "Thoughtful planning"
      description: "Each project begins with discovery and a roadmap that balances design, performance, and budget."
      icon: "🧭"
    - title: "Modern design"
      description: "Clean layouts, intuitive navigation, and responsive structure ensure every visitor has a smooth experience."
      icon: "💻"
    - title: "Quality execution"
      description: "Built with precision, tested for speed, and optimized for long-term reliability across all devices."
      icon: "⚙️"
    - title: "SEO & visibility"
      description: "Technical SEO, analytics setup, and Google Business alignment help your website get found by the right audience."
      icon: "📈"
    - title: "Ongoing partnership"
      description: "We remain available for updates, enhancements, and growth discussions well beyond launch day."
      icon: "🤝"
video:
  variant: "none" # Options: half, full, none
  background:
    tone: "gradient" # Options: none, gradient, solid, aurora
    color: null
  animation: true # Toggle video animation on/off
  eyebrow: "See us in action"
  title: "A day on site with our crew"
  intro: "From prep to final walkthrough, here’s how we keep projects moving smoothly."
  videoUrl: "" # External video URL (e.g., YouTube)
  localVideo: "/media/mainloop.mp4"
  posterUrl: ""
  caption: "A quick look at how we support neighbors every step of the way."
testimonials:
  variant: "none" # Options: grid, stack, none
  background:
    tone: "none" # Options: none, gradient, aurora
    color: null
  animation: true # Toggle testimonials animation on/off
  eyebrow: "What clients say"
  title: "Kind Words"
  intro: "Real feedback from neighbors who trusted Local Business Co."
booking:
  variant: "none" # Options: classic, none
  background:
    tone: "gradient" # Options: none, gradient, aurora
    color: null
  animation: true # Toggle booking animation on/off
  heading: "Book an Appointment"
  description: "Reserve a time that works best for you."
